In [1]:
import torch
import numpy as np
torch.__version__

'2.14.0+cpu'

tensor is a muti-dim matrix containing elements of a single data type

default data type of float32

In [2]:
s  = torch.tensor(5) # scalar
print(s.ndim)
print(s.type)
print(s.dtype)

0
<built-in method type of Tensor object at 0x0000016727650E10>
torch.int64


In [3]:
torch.tensor([[1,2,3],[4,5,6]],dtype=float).shape

torch.Size([2, 3])

In [4]:
torch.rand((2,3))

tensor([[0.2894, 0.4110, 0.8409],
        [0.0447, 0.3200, 0.2389]])

In [5]:
torch.randn(3,4)

tensor([[ 0.0268, -1.4820, -0.2380, -0.3117],
        [-1.0046,  0.3793,  1.3764, -1.2786],
        [-0.8104, -0.7365,  0.3344,  0.1557]])

In [6]:
x = torch.zeros((2,3))

### zeroes_like
It creates a new tensor completely filled with zeros that mirrors the exact shape (dimensions) and data type of an existing reference tensor.

In [7]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.arange(0,20,2).reshape((2,-1))

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [14]:
f = torch.tensor([1,2,3],dtype=torch.float64,device=None,requires_grad=False)
f

tensor([1., 2., 3.], dtype=torch.float64)

In [10]:
torch.empty(5,dtype=torch.int)

tensor([-1845295776,         536,           0,           0,           0],
       dtype=torch.int32)

In [16]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [15]:
torch.cuda.is_available()

False

In [ ]:
import torch
from torch import nn


